export interface VoiceRequest {
    productId: string;
    conversationId?: string;

    /**
     * Text generated by Speech-to-Text.
     *
     * In the first version of the voice agent,
     * STT happens before VoiceService.
     */
    transcript: string;
}

export interface VoiceResponse {
    conversationId: string;

    transcript: string;

    answer: string;

    tool?: string;

    toolResult?: unknown;
}