import mongoose from "mongoose";
import { LLMService } from "../../../services/llm.service";
import { SurveyModel, SurveyStatus } from "../models/Survey.model";
import { SurveyQuestionModel, QuestionType } from "../models/SurveyQuestion.model";
import { ProductModel } from "../../products/product.model";
import { CampaignModel, CampaignType } from "../../campaign/models/Campaign.model";

export interface GenerateSurveyInput {
    topic: string;
    productContext?: string;
    productId?: string;
    campaignId?: string;
    targetAudience?: string;
    questionCount?: number;
    channel?: "VOICE" | "CHAT" | "WEB";
}

export interface AISurveyGeneratedData {
    title: string;
    description: string;
    questions: Array<{
        questionText: string;
        voicePrompt?: string;
        questionType: QuestionType | string;
        description?: string;
        options?: string[];
        isRequired?: boolean;
        category?: string;
    }>;
}

export class AISurveyGeneratorService {
    /**
     * Generate a complete, intelligent survey with questions, options, and branching using LLM.
     */
    async generateSurvey(input: GenerateSurveyInput): Promise<any> {
        let productDetails = "";
        if (input.productId && mongoose.Types.ObjectId.isValid(input.productId)) {
            const product = await ProductModel.findById(input.productId).lean();
            if (product) {
                productDetails = `Product Name: ${product.name}\nDescription: ${product.description}\nFeatures: ${JSON.stringify((product as any).features || [])}`;
            }
        }

        const count = input.questionCount || 5;
        const systemPrompt = `You are an expert AI Survey Designer and Voice Sales Strategist.
Create a high-converting, professional survey tailored for ${input.channel || "VOICE/CHAT"} communication.

Supported question types:
- text (Open ended response)
- long_text (Detailed feedback)
- single_choice (Pick one from options)
- multiple_choice (Pick multiple from options)
- yes_no (Boolean yes/no)
- number (Numerical value)
- rating (1 to 5 star rating)
- scale (1 to 10 scale rating)
- date (Date format)
- frequency (Daily, Weekly, Monthly, Rarely, Never)
- price (Budget/pricing amount)
- product (Specific product interest)

Design questions that are natural to ask over a phone call or chat conversation. For each question, provide:
1. questionText: Standard readable text
2. voicePrompt: Conversational, friendly phrasing for AI voice agent to speak over a phone call
3. questionType: One of the supported question types above
4. options: Array of option strings (for single_choice, multiple_choice, frequency)
5. isRequired: true/false
6. category: e.g. "Demographics", "Pain Points", "Product Interest", "Budget", "Satisfaction"`;

        const userPrompt = `Generate a ${count}-question survey for the following requirements:
Topic: ${input.topic}
Target Audience: ${input.targetAudience || "General B2B/B2C Decision Makers"}
Product Context: ${productDetails || input.productContext || "AI Sales Intelligence Platform"}
Channel: ${input.channel || "VOICE_AND_CHAT"}

Return a JSON object with:
{
  "title": "Survey Title",
  "description": "Brief survey objective",
  "questions": [
    {
      "questionText": "How satisfied are you with your current sales qualification process?",
      "voicePrompt": "Could you rate how satisfied you currently are with your sales qualification process on a scale from 1 to 5?",
      "questionType": "rating",
      "options": ["1", "2", "3", "4", "5"],
      "isRequired": true,
      "category": "Satisfaction"
    }
  ]
}`;

        const generated = await LLMService.generateJSON<AISurveyGeneratedData>(
            systemPrompt,
            userPrompt,
            "{ title: string, description: string, questions: Array<{ questionText: string, voicePrompt?: string, questionType: string, options?: string[], isRequired?: boolean, category?: string }> }"
        );

        const dummyCampaignId = input.campaignId && mongoose.Types.ObjectId.isValid(input.campaignId)
            ? new mongoose.Types.ObjectId(input.campaignId)
            : new mongoose.Types.ObjectId();

        // Save Survey to database
        const survey: any = await SurveyModel.create({
            campaignId: dummyCampaignId,
            name: generated.title || input.topic,
            description: generated.description || `Survey generated by AI for ${input.topic}`,
            version: 1,
            status: SurveyStatus.DRAFT,
            language: "en-IN",
            createdBy: new mongoose.Types.ObjectId(),
            welcomeMessage: `Welcome! Thank you for taking a moment to share your feedback on ${input.topic}.`,
            endMessage: "Thank you for completing this survey! Your input helps us serve you better.",
        });

        // Save Questions to database
        const questionsToInsert = (generated.questions || []).map((q, idx) => ({
            surveyId: survey._id,
            questionId: `q_${Date.now()}_${idx + 1}`,
            text: q.questionText,
            type: (q.questionType || QuestionType.TEXT).toLowerCase(),
            aiPrompt: q.voicePrompt || q.description || "",
            options: (q.options || []).map((opt) => ({
                value: opt.toLowerCase().replace(/\s+/g, "_"),
                label: opt,
            })),
            required: q.isRequired ?? true,
            order: idx + 1,
        }));

        const savedQuestions = await SurveyQuestionModel.insertMany(questionsToInsert);

        if (input.campaignId && mongoose.Types.ObjectId.isValid(input.campaignId)) {
            await CampaignModel.findByIdAndUpdate(input.campaignId, {
                surveyId: survey._id,
                action: "SURVEY",
                type: CampaignType.SURVEY,
            });
        }

        return {
            survey,
            questions: savedQuestions,
        };
    }

    /**
     * Edit or expand an existing survey using natural language AI instructions.
     */
    async editSurveyWithAI(surveyId: string, instructions: string): Promise<any> {
        if (!surveyId || !mongoose.Types.ObjectId.isValid(surveyId)) {
            throw new Error("Invalid surveyId");
        }

        const survey: any = await SurveyModel.findById(surveyId);
        if (!survey) throw new Error("Survey not found");

        const existingQuestions = await SurveyQuestionModel.find({ surveyId: new mongoose.Types.ObjectId(surveyId) })
            .sort({ order: 1 })
            .lean();

        const systemPrompt = `You are an AI Survey Editor. You modify existing survey questions and metadata according to user instructions.`;

        const userPrompt = `Current Survey Title: ${survey.name}
Current Description: ${survey.description}
Current Questions: ${JSON.stringify(existingQuestions.map((q: any) => ({
            id: q._id,
            order: q.order,
            questionText: q.text,
            questionType: q.type,
            options: (q.options || []).map((o: any) => o.label || o.value),
            isRequired: q.required
        })))}

User Edit Instructions: "${instructions}"

Return modified survey JSON in the format:
{
  "title": "Updated Title",
  "description": "Updated Description",
  "questions": [
    {
      "questionText": "...",
      "voicePrompt": "...",
      "questionType": "single_choice",
      "options": ["..."],
      "isRequired": true,
      "category": "..."
    }
  ]
}`;

        const modified = await LLMService.generateJSON<AISurveyGeneratedData>(
            systemPrompt,
            userPrompt
        );

        if (modified.title) survey.name = modified.title;
        if (modified.description) survey.description = modified.description;
        await survey.save();

        if (modified.questions && modified.questions.length > 0) {
            // Replace questions
            await SurveyQuestionModel.deleteMany({ surveyId: survey._id });
            const newQuestions = modified.questions.map((q, idx) => ({
                surveyId: survey._id,
                questionId: `q_${Date.now()}_${idx + 1}`,
                text: q.questionText,
                type: (q.questionType || QuestionType.TEXT).toLowerCase(),
                aiPrompt: q.voicePrompt || q.description || "",
                options: (q.options || []).map((opt) => ({
                    value: opt.toLowerCase().replace(/\s+/g, "_"),
                    label: opt,
                })),
                required: q.isRequired ?? true,
                order: idx + 1,
            }));
            const saved = await SurveyQuestionModel.insertMany(newQuestions);
            return { survey, questions: saved };
        }

        return { survey, questions: existingQuestions };
    }

    /**
     * Import a survey from uploaded raw content (JSON, CSV, PDF, Word doc, or questionnaire text)
     */
    async importSurveyFromContent(input: {
        rawContent: string;
        fileName?: string;
        mimeType?: string;
        campaignId?: string;
        name?: string;
        createdBy?: string;
        channel?: "VOICE" | "CHAT" | "WEB";
    }): Promise<{ survey: any; questions: any[]; parsedCount: number }> {
        const { rawContent, fileName, campaignId, name, createdBy, channel = "VOICE" } = input;
        if (!rawContent || !rawContent.trim()) {
            throw new Error("File content is empty");
        }

        let surveyTitle = name || (fileName ? fileName.replace(/\.[^/.]+$/, "").replace(/[-_]/g, " ") : "Imported Survey");
        let surveyDesc = "Survey imported from uploaded document.";
        let parsedQuestions: Array<{
            questionText: string;
            voicePrompt?: string;
            questionType: string;
            options?: string[];
            isRequired?: boolean;
            category?: string;
        }> = [];

        // 1. Try direct JSON parsing
        try {
            const directJson = JSON.parse(rawContent.trim());
            if (Array.isArray(directJson)) {
                parsedQuestions = directJson.map((q: any) => ({
                    questionText: q.text || q.questionText || q.question || "Untitled Question",
                    voicePrompt: q.aiPrompt || q.voicePrompt || q.text || q.questionText,
                    questionType: q.type || q.questionType || "text",
                    options: Array.isArray(q.options)
                        ? q.options.map((o: any) => (typeof o === "string" ? o : o.label || o.value))
                        : [],
                    isRequired: q.required ?? q.isRequired ?? true,
                    category: q.category,
                }));
            } else if (typeof directJson === "object" && directJson !== null) {
                if (directJson.name || directJson.title) {
                    surveyTitle = directJson.name || directJson.title;
                }
                if (directJson.description) {
                    surveyDesc = directJson.description;
                }
                if (Array.isArray(directJson.questions)) {
                    parsedQuestions = directJson.questions.map((q: any) => ({
                        questionText: q.text || q.questionText || q.question || "Untitled Question",
                        voicePrompt: q.aiPrompt || q.voicePrompt || q.text || q.questionText,
                        questionType: q.type || q.questionType || "text",
                        options: Array.isArray(q.options)
                            ? q.options.map((o: any) => (typeof o === "string" ? o : o.label || o.value))
                            : [],
                        isRequired: q.required ?? q.isRequired ?? true,
                        category: q.category,
                    }));
                }
            }
        } catch {
            // Not raw JSON - parse via LLM
        }

        // 2. If questions were not extracted via direct JSON, use LLM to parse document/CSV/text
        if (parsedQuestions.length === 0) {
            const systemPrompt = `You are an expert Survey Document Parser and Voice AI Specialist.
Your task is to extract all questions, answer choices, question types, and voice-optimized prompts from the uploaded document or questionnaire text.

Supported question types:
- text (Open ended response)
- long_text (Detailed open ended feedback)
- single_choice (Pick one option from list)
- multiple_choice (Select multiple options)
- yes_no (Boolean yes/no question)
- number (Numeric answer)
- rating (1 to 5 scale)
- scale (1 to 10 scale)
- date (Date answer)
- frequency (Daily, Weekly, Monthly, Rarely, Never)
- price (Pricing or budget amount)
- product (Product choice or feature interest)

For each question:
1. questionText: Clean, well-formatted question text.
2. voicePrompt: Conversational spoken wording for an AI sales agent to ask over a phone call.
3. questionType: Exactly one of the supported question types above.
4. options: Array of option strings (for single_choice, multiple_choice, frequency, yes_no).
5. isRequired: true/false (default true).
6. category: High-level category (e.g. Satisfaction, Qualification, Budget, Pain Points).
7. conditions: Optional array of logic conditions if document specifies ending the call or jumping (e.g. if choice says "No – End the call", include [{ "operator": "equals", "value": "no", "action": "end_survey" }]).`;

            const userPrompt = `Document Filename: ${fileName || "Uploaded Questionnaire"}
Target Channel: ${channel}
Extracted Document Content:
---
${rawContent.slice(0, 15000)}
---

Extract the survey title, description, and every survey question in the document into clean JSON:
{
  "title": "${surveyTitle}",
  "description": "${surveyDesc}",
  "questions": [
    {
      "questionText": "Question text here?",
      "voicePrompt": "Conversational phone prompt here?",
      "questionType": "single_choice",
      "options": ["Option 1", "Option 2"],
      "isRequired": true,
      "category": "Qualification",
      "conditions": [
        { "operator": "equals", "value": "no", "action": "end_survey" }
      ]
    }
  ]
}`;

            const aiResult = await LLMService.generateJSON<AISurveyGeneratedData>(
                systemPrompt,
                userPrompt,
                "{ title: string, description: string, questions: Array<{ questionText: string, voicePrompt?: string, questionType: string, options?: string[], isRequired?: boolean, category?: string, conditions?: Array<{ operator: string, value: string, action: string }> }> }"
            );

            if (aiResult.title) surveyTitle = aiResult.title;
            if (aiResult.description) surveyDesc = aiResult.description;
            if (Array.isArray(aiResult.questions) && aiResult.questions.length > 0) {
                parsedQuestions = aiResult.questions;
            }
        }

        if (parsedQuestions.length === 0) {
            throw new Error("Could not detect any valid survey questions in the uploaded file.");
        }

        const dummyCampaignId = campaignId && mongoose.Types.ObjectId.isValid(campaignId)
            ? new mongoose.Types.ObjectId(campaignId)
            : new mongoose.Types.ObjectId();

        const userObjectId = createdBy && mongoose.Types.ObjectId.isValid(createdBy)
            ? new mongoose.Types.ObjectId(createdBy)
            : new mongoose.Types.ObjectId();

        // Create the Survey
        const survey: any = await SurveyModel.create({
            campaignId: dummyCampaignId,
            name: surveyTitle,
            description: surveyDesc,
            version: 1,
            status: SurveyStatus.DRAFT,
            language: "en-IN",
            createdBy: userObjectId,
            welcomeMessage: `Welcome! Thank you for taking a moment to complete this survey on ${surveyTitle}.`,
            endMessage: "Thank you for completing this survey! Your responses have been recorded.",
        });

        // Save Questions
        const questionsToInsert = parsedQuestions.map((q: any, idx) => {
            const qId = `q_${Date.now()}_${idx + 1}`;
            const textLower = (q.questionText || "").toLowerCase();
            const conditions = (q.conditions || []).map((c: any) => ({
                field: c.field || qId,
                operator: c.operator || "equals",
                value: c.value,
                action: c.action || "end_survey",
                nextQuestionId: c.nextQuestionId,
            }));

            // If question is specifically "why not buy" or "only if ... is no"
            const isNoBranchQuestion = /only if.*(?:is\s+no|\bno\b)/i.test(textLower) || /why will you not buy/i.test(textLower);
            if (isNoBranchQuestion && conditions.length === 0) {
                conditions.push({
                    field: qId,
                    operator: "is_not_empty",
                    value: "",
                    action: "end_survey",
                });
            }

            return {
                surveyId: survey._id,
                questionId: qId,
                text: q.questionText,
                type: (q.questionType || QuestionType.TEXT).toLowerCase(),
                aiPrompt: q.voicePrompt || q.questionText,
                options: (q.options || []).map((opt: any) => ({
                    value: String(opt).toLowerCase().replace(/\s+/g, "_"),
                    label: String(opt),
                })),
                required: q.isRequired ?? true,
                order: idx + 1,
                conditions,
            };
        });

        const savedQuestions = await SurveyQuestionModel.insertMany(questionsToInsert);

        if (campaignId && mongoose.Types.ObjectId.isValid(campaignId)) {
            await CampaignModel.findByIdAndUpdate(campaignId, {
                surveyId: survey._id,
                action: "SURVEY",
                type: CampaignType.SURVEY,
            });
        }

        return {
            survey,
            questions: savedQuestions,
            parsedCount: savedQuestions.length,
        };
    }

    /**
     * Import questions into an existing survey from uploaded raw content
     */
    async importQuestionsToExistingSurvey(
        surveyId: string,
        rawContent: string,
        options: { append?: boolean; fileName?: string } = {}
    ): Promise<{ survey: any; questions: any[]; addedCount: number }> {
        if (!surveyId || !mongoose.Types.ObjectId.isValid(surveyId)) {
            throw new Error("Invalid surveyId");
        }

        const survey: any = await SurveyModel.findById(surveyId);
        if (!survey) throw new Error("Survey not found");

        const existingQuestions = await SurveyQuestionModel.find({ surveyId: new mongoose.Types.ObjectId(surveyId) })
            .sort({ order: 1 })
            .lean();

        let parsedQuestions: Array<{
            questionText: string;
            voicePrompt?: string;
            questionType: string;
            options?: string[];
            isRequired?: boolean;
            category?: string;
        }> = [];

        // Try direct JSON parsing
        try {
            const directJson = JSON.parse(rawContent.trim());
            const qList = Array.isArray(directJson) ? directJson : directJson.questions;
            if (Array.isArray(qList)) {
                parsedQuestions = qList.map((q: any) => ({
                    questionText: q.text || q.questionText || q.question || "Untitled Question",
                    voicePrompt: q.aiPrompt || q.voicePrompt || q.text || q.questionText,
                    questionType: q.type || q.questionType || "text",
                    options: Array.isArray(q.options)
                        ? q.options.map((o: any) => (typeof o === "string" ? o : o.label || o.value))
                        : [],
                    isRequired: q.required ?? q.isRequired ?? true,
                    category: q.category,
                }));
            }
        } catch {
            // Not raw JSON
        }

        if (parsedQuestions.length === 0) {
            const systemPrompt = `You are an expert Survey Document Parser. Extract survey questions from the provided questionnaire text or document.`;
            const userPrompt = `Document: ${options.fileName || "Uploaded snippet"}
Content:
---
${rawContent.slice(0, 15000)}
---
Extract all questions into JSON:
{
  "questions": [
    {
      "questionText": "Question text?",
      "voicePrompt": "Conversational prompt?",
      "questionType": "single_choice",
      "options": ["A", "B"],
      "isRequired": true
    }
  ]
}`;
            const aiResult = await LLMService.generateJSON<{ questions: any[] }>(
                systemPrompt,
                userPrompt
            );
            if (Array.isArray(aiResult.questions)) {
                parsedQuestions = aiResult.questions;
            }
        }

        if (parsedQuestions.length === 0) {
            throw new Error("No questions could be extracted from the content");
        }

        if (!options.append) {
            await SurveyQuestionModel.deleteMany({ surveyId: survey._id });
        }

        const startOrder = options.append ? existingQuestions.length : 0;
        const questionsToInsert = parsedQuestions.map((q, idx) => ({
            surveyId: survey._id,
            questionId: `q_${Date.now()}_${idx + 1}`,
            text: q.questionText,
            type: (q.questionType || QuestionType.TEXT).toLowerCase(),
            aiPrompt: q.voicePrompt || q.questionText,
            options: (q.options || []).map((opt) => ({
                value: String(opt).toLowerCase().replace(/\s+/g, "_"),
                label: String(opt),
            })),
            required: q.isRequired ?? true,
            order: startOrder + idx + 1,
        }));

        const saved = await SurveyQuestionModel.insertMany(questionsToInsert);
        const allQuestions = await SurveyQuestionModel.find({ surveyId: survey._id }).sort({ order: 1 });

        return {
            survey,
            questions: allQuestions,
            addedCount: saved.length,
        };
    }
}
