import { AgentChannel } from "../agent/agent.types";

export { AgentChannel };


export interface VoiceRequest {
    productId: string;
    conversationId?: string;

    /**
     * Text generated by Speech-to-Text.
     *
     * In the first version of the voice agent,
     * STT happens before VoiceService.
     */
    transcript: string;
    channel?: AgentChannel;
}

export interface VoiceResponse {
    conversationId: string;

    transcript: string;

    answer: string;

    audioBase64: string;

    mimeType: string;

    tool?: string;

    toolResult?: unknown;

    durationMS?: number;
}